import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

// -- PrimeNG Modules --
import {
  // AccordionModule,
  // AutoCompleteModule,
  // BlockUIModule,
  // BreadcrumbModule,
  // ButtonModule,
  CalendarModule,
  // CaptchaModule,
  // CardModule,
  // CarouselModule,
  ChartModule,
  CheckboxModule,
  // ChipsModule,
  // CodeHighlighterModule,
  // ColorPickerModule,
  // ConfirmDialogModule,
  // ContextMenuModule,
  // DataGridModule,
  // DataListModule,
  // DataScrollerModule,
  // DataTableModule,
  // DeferModule,
  // DialogModule,
  // DragDropModule,
  // DropdownModule,
  EditorModule,
  // FieldsetModule,
  FileUploadModule,
  // GalleriaModule,
  // GMapModule,
  // GrowlModule,
  // InplaceModule,
  // InputMaskModule,
  // InputSwitchModule,
  // InputTextareaModule,
  InputTextModule,
  // KeyFilterModule,
  // LightboxModule,
  // ListboxModule,
  // MegaMenuModule,
  // MenubarModule,
  // MenuModule,
  // MessageModule,
  // MessagesModule,
  // MultiSelectModule,
  // OrderListModule,
  // OrganizationChartModule,
  // OverlayPanelModule,
  // PaginatorModule,
  // PanelMenuModule,
  // PanelModule,
  // PasswordModule,
  // PickListModule,
  // ProgressBarModule,
  // ProgressSpinnerModule,
  RadioButtonModule,
  // RatingModule,
  // ScheduleModule,
  // ScrollPanelModule,
  // SelectButtonModule,
  // SharedModule,
  // SidebarModule,
  // SlideMenuModule,
  // SliderModule,
  // SpinnerModule,
  // SplitButtonModule,
  // StepsModule,
  // TabMenuModule,
  TabViewModule,
  // TerminalModule,
  // TieredMenuModule,
  // ToggleButtonModule,
  // ToolbarModule,
  // TooltipModule,
  // TreeModule,
  // TreeTableModule,
  // TriStateCheckboxModule,
} from 'primeng/primeng';

@NgModule({
  imports: [
    CommonModule,
    BrowserAnimationsModule,
    // PrimeNG Modules
    CalendarModule,
    ChartModule,
    CheckboxModule,
    EditorModule,
    FileUploadModule,
    InputTextModule,
    RadioButtonModule,
    TabViewModule,
  ],
  providers: [
  ],
  declarations: [
  ],
  exports: [
    CalendarModule,
    ChartModule,
    CheckboxModule,
    EditorModule,
    FileUploadModule,
    InputTextModule,
    RadioButtonModule,
    TabViewModule,
  ]
})
export class PrimengModule { }
